/**
 * Verified OPNet ecosystem projects from vibecode.finance/ecosystem?verified=1
 * All 43 featured verified dApps.
 */

export type EcoCategory =
  | 'DeFi'
  | 'Gaming'
  | 'NFT & Marketplace'
  | 'Tools & Infrastructure'
  | 'Social & DAO';

export interface EcoProject {
  name: string;
  description: string;
  category: EcoCategory;
  tags: string[];
  icon: string;
  color: string;
  url: string;
  status: 'Live' | 'Beta' | 'Building';
  verified: true;
}

export const CATEGORY_COLORS: Record<EcoCategory, string> = {
  'DeFi':                   '#f7931a',
  'Gaming':                 '#22d3ee',
  'NFT & Marketplace':      '#e879f9',
  'Tools & Infrastructure': '#34d399',
  'Social & DAO':           '#7b3fe4',
};

export const CATEGORY_ICONS: Record<EcoCategory, string> = {
  'DeFi':                   '💰',
  'Gaming':                 '🎮',
  'NFT & Marketplace':      '🖼️',
  'Tools & Infrastructure': '🔧',
  'Social & DAO':           '🏛️',
};

const ECO_BASE = 'https://vibecode.finance/ecosystem?verified=1';

export const PROJECTS: EcoProject[] = [
  /* ── DeFi ──────────────────────────────────────────────────────────────── */
  {
    name: 'Motoswap',
    description: 'Leading AMM and DEX infrastructure for Bitcoin L1 — swap any OP20 tokens natively on-chain.',
    category: 'DeFi',
    tags: ['DEX', 'AMM', 'Swap'],
    icon: '🔄',
    color: '#f7931a',
    url: 'https://motoswap.org',
    status: 'Live',
    verified: true,
  },
  {
    name: 'SignalFi',
    description: 'Self-sustaining DeFi hub combining OTC escrow, revenue vault, and auto-compound staking on Bitcoin.',
    category: 'DeFi',
    tags: ['Staking', 'Yield', 'OTC'],
    icon: '📡',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'NEXFI Protocol',
    description: 'Lending, borrowing & yield aggregation with Yearn-style auto-compounding strategies on Bitcoin L1.',
    category: 'DeFi',
    tags: ['Lending', 'Borrowing', 'Yield'],
    icon: '🏦',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OPSTAKE',
    description: 'Auto-compound staking protocol native to Bitcoin L1. Stake, earn, and compound — fully on-chain.',
    category: 'DeFi',
    tags: ['Staking', 'Auto-Compound'],
    icon: '⚡',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Aura Finance',
    description: 'Multi-tier staking vaults with APY ranging 4.5%–38.5%. Lock BTC-native tokens for boosted yields.',
    category: 'DeFi',
    tags: ['Staking', 'Vaults', 'veTokens'],
    icon: '✨',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'PuSd Vaults',
    description: 'Stablecoin protocol with collateralized minting and yield generation secured by Bitcoin.',
    category: 'DeFi',
    tags: ['Stablecoin', 'Vaults', 'Yield'],
    icon: '💵',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'bitlend-opnet',
    description: 'Bitcoin L1 lending protocol — deposit collateral, borrow stablecoins in seconds via OP_NET.',
    category: 'DeFi',
    tags: ['Lending', 'Collateral', 'Stablecoin'],
    icon: '🏧',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OPfun',
    description: 'No-code OP_20 token launcher — deploy custom tokens to Bitcoin L1 in 60 seconds.',
    category: 'DeFi',
    tags: ['Launchpad', 'Token', 'No-Code'],
    icon: '🚀',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'BitLaunch',
    description: 'No-code launchpad with token presales, vesting schedules, and liquidity locks on Bitcoin.',
    category: 'DeFi',
    tags: ['Launchpad', 'Presale', 'Vesting'],
    icon: '🛸',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OP_LAUNCH',
    description: 'Modular DeFi launchpad for token creation, liquidity management, and community distribution.',
    category: 'DeFi',
    tags: ['Launchpad', 'Liquidity', 'Token'],
    icon: '🎯',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OpNet AI',
    description: 'AI-powered auto-investment bot for DeFi portfolio optimization — plug in your wallet, let it earn.',
    category: 'DeFi',
    tags: ['AI', 'Portfolio', 'Yield'],
    icon: '🤖',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'SatForge',
    description: 'Token deployment dashboard with smart contract parameterization for advanced OP20 configurations.',
    category: 'DeFi',
    tags: ['Token', 'Deploy', 'Dev'],
    icon: '⚙️',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'veBTC Gauge',
    description: 'veTokenomics system with lock/vote/bribe mechanics — direct liquidity emissions on Bitcoin L1.',
    category: 'DeFi',
    tags: ['veTokens', 'Governance', 'Gauges'],
    icon: '🗳️',
    color: '#f7931a',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },

  /* ── Gaming ─────────────────────────────────────────────────────────────── */
  {
    name: 'BlockBet',
    description: 'Prediction market for Bitcoin block hash parity — bet on EVEN or ODD, provably fair on-chain.',
    category: 'Gaming',
    tags: ['Prediction', 'Betting', 'On-Chain'],
    icon: '🎲',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'FLIP GAME',
    description: 'On-chain coin flip — pick heads or tails, double your BTC or lose it. Instant settlement.',
    category: 'Gaming',
    tags: ['Casino', 'Coin Flip', 'Instant'],
    icon: '🪙',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Poker',
    description: 'Multiplayer Texas Hold\'em built on OPNet — real BTC stakes, fully on-chain card logic.',
    category: 'Gaming',
    tags: ['Poker', 'Multiplayer', 'Cards'],
    icon: '♠️',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: '2048',
    description: 'Fully on-chain 2048 puzzle game with leaderboard competition and BTC prize pools.',
    category: 'Gaming',
    tags: ['Puzzle', 'Leaderboard', 'Competitive'],
    icon: '🧩',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OPacmaNET',
    description: 'Nostalgic Pac-Man style arcade game deployed entirely on OPNet Bitcoin smart contracts.',
    category: 'Gaming',
    tags: ['Arcade', 'Retro', 'On-Chain'],
    icon: '👾',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Block Battle',
    description: 'Meme voting battle game — submit your meme, rally the community, the strongest meme survives.',
    category: 'Gaming',
    tags: ['Meme', 'Voting', 'Community'],
    icon: '⚔️',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'VibeRaffle',
    description: 'On-chain BTC lottery with provably-fair random draws. Buy tickets, win big on Bitcoin.',
    category: 'Gaming',
    tags: ['Lottery', 'Raffle', 'Provably Fair'],
    icon: '🎟️',
    color: '#22d3ee',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },

  /* ── NFT & Marketplace ──────────────────────────────────────────────────── */
  {
    name: 'Motocats',
    description: 'Iconic NFT collectibles racing on Bitcoin. Buy, sell, and race your Motocat on-chain.',
    category: 'NFT & Marketplace',
    tags: ['NFT', 'OP721', 'Racing'],
    icon: '🏎️',
    color: '#e879f9',
    url: 'https://magiceden.io/ordinals/marketplace/motocats',
    status: 'Live',
    verified: true,
  },
  {
    name: 'FracMarket',
    description: 'NFT fractional marketplace — fractionalize any OP721 NFT into 1M tradeable shares.',
    category: 'NFT & Marketplace',
    tags: ['NFT', 'Fractionalization', 'Marketplace'],
    icon: '✂️',
    color: '#e879f9',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'AgentVault',
    description: 'AI-native NFT marketplace — discover, trade, and curate AI-generated art on Bitcoin.',
    category: 'NFT & Marketplace',
    tags: ['NFT', 'AI Art', 'Marketplace'],
    icon: '🏛️',
    color: '#e879f9',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'Vibe Check',
    description: 'Generative art dApp — select your emotional state to mint a unique SVG NFT on Bitcoin.',
    category: 'NFT & Marketplace',
    tags: ['Generative Art', 'Mint', 'SVG'],
    icon: '🎨',
    color: '#e879f9',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'MyTXO',
    description: 'Decentralized social platform where every user deploys their own OP721 contract as identity.',
    category: 'NFT & Marketplace',
    tags: ['Social', 'Identity', 'OP721'],
    icon: '🌐',
    color: '#e879f9',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OP_Token Forge',
    description: 'One-click OP_20 token factory — configure name, supply, and taxes in a single transaction.',
    category: 'NFT & Marketplace',
    tags: ['Token Factory', 'OP20', 'No-Code'],
    icon: '🔨',
    color: '#e879f9',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },

  /* ── Tools & Infrastructure ─────────────────────────────────────────────── */
  {
    name: 'OPScan',
    description: 'The official block explorer for OPNet — browse transactions, contracts, tokens, and events.',
    category: 'Tools & Infrastructure',
    tags: ['Explorer', 'Analytics', 'Indexer'],
    icon: '🔍',
    color: '#34d399',
    url: 'https://opscan.io',
    status: 'Live',
    verified: true,
  },
  {
    name: 'OP_WALLET',
    description: 'Browser extension wallet with native OP_NET support — manage BTC, OP20 tokens, and OP721 NFTs.',
    category: 'Tools & Infrastructure',
    tags: ['Wallet', 'Extension', 'Browser'],
    icon: '👛',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OPTools',
    description: 'Developer utilities for the OPNet ecosystem — ABI encoder, calldata inspector, event parser.',
    category: 'Tools & Infrastructure',
    tags: ['Dev Tools', 'ABI', 'Debug'],
    icon: '🛠️',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Opnet-Multisender',
    description: 'Batch token and BTC sender — distribute to 100+ addresses in a single optimized transaction.',
    category: 'Tools & Infrastructure',
    tags: ['Batch', 'Airdrop', 'Multisend'],
    icon: '📤',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Fee Estimator',
    description: 'Real-time transaction fee calculator with wallet connection for accurate OP_NET gas estimation.',
    category: 'Tools & Infrastructure',
    tags: ['Fees', 'Gas', 'Calculator'],
    icon: '⛽',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OP_Sign',
    description: 'Document notarization protocol — prove a document existed at a specific Bitcoin block height.',
    category: 'Tools & Infrastructure',
    tags: ['Notarization', 'Proof', 'Documents'],
    icon: '✍️',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'OctoSig',
    description: 'Multi-signature shared wallet for BTC and OP-20 tokens — M-of-N signing with full on-chain enforcement.',
    category: 'Tools & Infrastructure',
    tags: ['MultiSig', 'Wallet', 'Security'],
    icon: '🐙',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Daily BTC Tip Jar',
    description: 'Micro-tip system with quantum-safe ML-DSA signatures — send sats to any creator on Bitcoin.',
    category: 'Tools & Infrastructure',
    tags: ['Tips', 'ML-DSA', 'Payments'],
    icon: '☕',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
  {
    name: 'Bob (AI Agent)',
    description: 'OPNet\'s official AI assistant powered by Llama — interact with the protocol through natural language.',
    category: 'Tools & Infrastructure',
    tags: ['AI', 'Assistant', 'Agent'],
    icon: '🤖',
    color: '#34d399',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },

  /* ── Social & DAO ────────────────────────────────────────────────────────── */
  {
    name: 'QuadFund BTC',
    description: 'Quadratic funding protocol with community matching pools — fund public goods on Bitcoin.',
    category: 'Social & DAO',
    tags: ['Funding', 'Quadratic', 'Public Goods'],
    icon: '🌱',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OnChainTicketing',
    description: 'Event ticketing secured by Bitcoin L1 — mint, resell, and verify tickets as OP721 NFTs.',
    category: 'Social & DAO',
    tags: ['Ticketing', 'Events', 'NFT'],
    icon: '🎫',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OPWork',
    description: 'Decentralized freelance marketplace with crypto payments — hire talent and pay in BTC natively.',
    category: 'Social & DAO',
    tags: ['Freelance', 'Marketplace', 'Work'],
    icon: '💼',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'BitOracle',
    description: 'Trustless prediction market for crypto, sports, and politics — bet on outcomes with BTC.',
    category: 'Social & DAO',
    tags: ['Prediction', 'Oracle', 'Markets'],
    icon: '🔮',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'OPQuestFi',
    description: 'Quest platform combining social tasks with DeFi interactions — earn rewards for on-chain activity.',
    category: 'Social & DAO',
    tags: ['Quests', 'Rewards', 'Social'],
    icon: '🗺️',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'HabiFi',
    description: 'Habit-staking protocol — stake BTC on your habits and earn yield for consistency.',
    category: 'Social & DAO',
    tags: ['Habits', 'Staking', 'Accountability'],
    icon: '💪',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Beta',
    verified: true,
  },
  {
    name: 'The Bitcoin DeFi Bible',
    description: 'Comprehensive open guide to OP_NET, native Bitcoin yield, and the DeFi stack on L1.',
    category: 'Social & DAO',
    tags: ['Education', 'Guide', 'DeFi'],
    icon: '📖',
    color: '#7b3fe4',
    url: ECO_BASE,
    status: 'Live',
    verified: true,
  },
];

export const ALL_CATEGORIES: EcoCategory[] = [
  'DeFi',
  'Gaming',
  'NFT & Marketplace',
  'Tools & Infrastructure',
  'Social & DAO',
];

export function getByCategory(cat: EcoCategory): EcoProject[] {
  return PROJECTS.filter((p) => p.category === cat);
}
